export const REQUEST_BOARD_LIST_TO_SPRING = 'REQUEST_BOARD_LIST_TO_SPRING'
export const REQUEST_BOARD_TO_SPRING = 'REQUEST_BOARD_TO_SPRING'
export const REQUEST_REPLY_LIST_FROM_SPRING = 'REQUEST_REPLY_LIST_FROM_SPRING'