export const REQUEST_ADD_CART_LIST_TO_SPRING = 'REQUEST_ADD_CART_LIST_TO_SPRING'
export const REQUEST_SELFSALAD_TO_SPRING = 'REQUEST_SELFSALAD_TO_SPRING'
export const REQUEST_ORDER_INFO_FROM_SPRING = "REQUEST_ORDER_INFO_FROM_SPRING"

export const REQUEST_COMPLETE_ORDER_TO_SPRING = "REQUEST_COMPLETE_ORDER_TO_SPRING"
