export const REQUEST_SIGN_IN_TOKEN_FROM_SPRING = 'REQUEST_SIGN_IN_TOKEN_FROM_SPRING'
export const SIGN_IN_VALUE = 'SIGN_IN_VALUE'
export const USER_TOKEN = 'USER_TOKEN'
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED'