export const REQUEST_BOARD_LIST_TO_SPRING = 'REQUEST_BOARD_LIST_TO_SPRING'
export const REQUEST_BOARD_TO_SPRING = 'REQUEST_BOARD_TO_SPRING'
export const REQUEST_SIGN_IN_TOKEN_FROM_SPRING = 'REQUEST_SIGN_IN_TOKEN_FROM_SPRING'
