export const REQUEST_BOARD_LIST_TO_SPRING = 'REQUEST_BOARD_LIST_TO_SPRING'
export const REQUEST_BOARD_TO_SPRING = 'REQUEST_BOARD_TO_SPRING'

export const REQUEST_SIDEPRODUCT_LIST_TO_SPRING = 'REQUEST_SIDEPRODUCT_LIST_TO_SPRING'
export const REQUEST_SIDEPRODUCT_TO_SPRING = 'REQUEST_SIDEPRODUCT_TO_SPRING'

export const REQUEST_SIGN_IN_TOKEN_FROM_SPRING = 'REQUEST_SIGN_IN_TOKEN_FROM_SPRING'
export const SIGN_IN_VALUE = 'SIGN_IN_VALUE'
export const USER_TOKEN = 'USER_TOKEN'


export const REQUEST_PRODUCT_TO_SPRING = 'REQUEST_PRODUCT_TO_SPRING'
export const REQUEST_PRODUCT_LIST_TO_SPRING = 'REQUEST_PRODUCT_LIST_TO_SPRING'
export const REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING = 'REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING'

export const REQUEST_INGREDIENT_LIST_TO_SPRING = 'REQUEST_INGREDIENT_LIST_TO_SPRING'
export const REQUEST_INGREDIENT_TO_SPRING = 'REQUEST_INGREDIENT_TO_SPRING'
export const REQUEST_INGREDIENT_CATEGORY_TO_SPRING = 'REQUEST_INGREDIENT_CATEGORY_TO_SPRING'
export const REQUEST_INGREDIENT_IMG_TO_SPRING = 'REQUEST_INGREDIENT_IMG_TO_SPRING'

