export const REQUEST_PRODUCT_TO_SPRING = 'REQUEST_PRODUCT_TO_SPRING'
export const REQUEST_PRODUCT_LIST_TO_SPRING = 'REQUEST_PRODUCT_LIST_TO_SPRING'
export const REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING = 'REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING'

export const REQUEST_READ_REVIEW_TO_SPRING = 'REQUEST_READ_REVIEW_TO_SPRING'
export const REQUEST_REVIEW_IMAGE_TO_SPRING = 'REQUEST_REVIEW_IMAGE_TO_SPRING'
export const REQUEST_MY_REVIEW_TO_SPRING = 'REQUEST_MY_REVIEW_TO_SPRING'

export const REQUEST_FAVORITE_LIST_TO_SPRING = 'REQUEST_FAVORITE_LIST_TO_SPRING'
export const REQUEST_FAVORITE_INFO_TO_SPRING = 'REQUEST_FAVORITE_INFO_TO_SPRING'
export const SET_FAVORITE_INFO = 'SET_FAVORITE_INFO'
export const INCREMENT_VIEW_CNT = 'INCREMENT_VIEW_CNT'