export const REQUEST_PRODUCT_TO_SPRING = 'REQUEST_PRODUCT_TO_SPRING'
export const REQUEST_PRODUCT_LIST_TO_SPRING = 'REQUEST_PRODUCT_LIST_TO_SPRING'
export const REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING = 'REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING'

export const REQUEST_READ_REVIEW_TO_SPRING = 'REQUEST_READ_REVIEW_TO_SPRING'
export const REQUEST_REVIEW_IMAGE_TO_SPRING = 'REQUEST_REVIEW_IMAGE_TO_SPRING'

